### ISSUE TITLE
Laser and Rs485 switch

### ISSUE THREAD

**Issue by matus1504** [Spark-Concepts/xPro-V5#108]
How can I choose between spindle and laser without touching the Rs485/Pwm switch?
"Changing between the different control options requires the appropriate firmware to be installed"
What do you mean about it?
I can't find a solution.

**Comment by Nastyfast44** [comment]
![FAB838E6-3655-40CC-A17C-BF4E46204E4E](https://user-images.githubusercontent.com/98447903/151489765-9c3f86cf-833a-412a-8fc5-76fa8b8ce32d.png)
Choose the file that relates to your emergency stop switch. The lever on your xpro will swap between the two (pwm& rs485). Don’t use anything on the old firmware page.  Don’t use the laser firmware either unless u have a bulkman laser. 

Link to firmware in case pic doesn’t go through. 

https://github.com/Spark-Concepts/xPro-V5/tree/main/Firmware

**Comment by Nastyfast44** [comment]
To my knowledge which this fixed my issue 5 min ago. This is a cross between the two and works for both
