### ISSUE TITLE
E Stop NC Switch

### ISSUE THREAD

**Issue by stfarley** [Spark-Concepts/xPro-V5#11]
I have the Estop switch working. However it is Backwards.
i.e. you have to press it for run and pull it to stop.
I don't see a polarity setting for this anywhere.

**Comment by Spark-Concepts** [comment]
Look at the backside of your estop button - it should have a switch symbol and marked either "NC" or "NO"
[NC_e-stop-hookup&bin.zip](https://github.com/Spark-Concepts/xPro-V5/files/6245872/NC_e-stop-hookup.bin.zip)
[NO_e-stop-hookup&bin.zip](https://github.com/Spark-Concepts/xPro-V5/files/6245873/NO_e-stop-hookup.bin.zip)

If your switch is NC:
![NC_Estop](https://user-images.githubusercontent.com/8650709/113339680-d9e2db80-92f8-11eb-81a4-dec471663761.jpg)

If your switch is NO:
![NO_Estop](https://user-images.githubusercontent.com/8650709/113340831-62ae4700-92fa-11eb-97ca-db85d737364a.jpg)

**Comment by stfarley** [comment]
Ah Thanks, That did the trick
