### ISSUE TITLE
Cooling fan stopped working

### ISSUE THREAD

**Issue by mwipp66** [Spark-Concepts/xPro-V5#111]
I think there may be something wrong with my controller. I previously had everything working as it should for the stepper motors and limit switches. While hooking up the spindle i was having some issues with the controller communicating with the VFD through rs485. Since i was having issues, i decided to reset everything (VFD settings, controller firmware and GRBL settings). After re-applying the firmware and re-setting GRBL settings, i started setting up my settings for my machine. As i was working on this i noticed the cooling fan on the controller was no longer spinning, when i got closer i also noticed a small amount of white smoke, so i shut everything down instantly.

Sparkconcepts, are you able to help me out here?

The controller was purchased through bulkman3d with my queenbee kit. Just received everything late January

**Comment by Spark-Concepts** [comment]
***Note: the cooling fan is temperature controlled - therefore it's not always going to be ON (load dependent)***

That said, it's possible the magic smoke leaked out from the cooling fan. 

If you're still having issues please reach out to us via:
https://www.spark-concepts.com/contact-us-1/
