### ISSUE TITLE
Y axis problem 

### ISSUE THREAD

**Issue by AbdullahAwwadSh** [Spark-Concepts/xPro-V5#117]
Hi

   My stepper motor makes a loud sound in the y axis and a less noisy sound in the x axis and quiet in the remaining axes 

The problem here is in xpro v5 controller 
Please watch the video

[Explain the problem](https://youtu.be/oPh4KUZ-zKY)

**Comment by Spark-Concepts** [comment]
If you haven't already, please contact us directly at https://www.spark-concepts.com/contact-us-1/ for resolution
