### ISSUE TITLE
Overheated motors

### ISSUE THREAD

**Issue by Wilson-Diaz-V** [Spark-Concepts/xPro-V5#118]
A question on how I can reduce the amperage, on circuit, that reaches my stepper motors, because they overheat too much when working, my motors consume only 3.8 amps., thanks

**Comment by Spark-Concepts** [comment]
[$X/Current/Run thru $C/Current/Run $140 thru $145 – [X,Y,Z,A,B,C] Stepper Run Current (extended settings)](https://github.com/Spark-Concepts/xPro-V5/wiki/Changing-settings#xcurrenthold-thru-ccurrenthold-or-150-thru-155--xyzabc--stepper-idle-current-extended-settings)

This is the run current in amperes for Trinamic SPI stepper drivers. This is RMS current, not MAX current - to calculate this setting, looking up the maximum current for your motor and multiply by 0.707. Example: Most Nema23 motors are rated for 2.8Amax therefore this setting = 2.8 * 0.707 = 1.97. * *Note: it is not great to run motor at max current for extended periods, would recommend setting this to roughly 90% of the calculated RMS current - for our example we would set our standard Nema28, with a 2.8A max, to a value of 1.8 for this setting

e.g.
```
$140 = 1.8
$141 = 1.8
$142 = 1.8
$143 = 1.8
```

[$X/Current/Hold thru $C/Current/Hold or $150 thru $155 – [X,Y,Z,A,B,C]](https://github.com/Spark-Concepts/xPro-V5/wiki/Changing-settings#xcurrenthold-thru-ccurrenthold-or-150-thru-155--xyzabc--stepper-idle-current-extended-settings) 

Stepper Idle Current (extended settings)
This is the hold current in amperes for Trinamic SPI stepper drivers. This is RMS current, not MAX current - generally, we recommend setting this to 50% to 75% of the Run current value - in our example, we would set this to 1.1
e.g.
```
$150 = 1.1
$151 = 1.1
$152 = 1.1
$153 = 1.1
```
