### ISSUE TITLE
Power connector burned

### ISSUE THREAD

**Issue by wildfang** [Spark-Concepts/xPro-V5#120]
Hi.

My xPro-5 just stopped in the middle of a job. When I took a closer look, I noticed that the 24v connector melted.

I don't know how this happened, I used cables of proper weight with proper ferules that sit really tight. The connector itself was pressed into place like it should. It wasn't loose and it didn't wiggle.

I haven't used it more than 6 hours in total, so I'm not happy.

Can you please advice what to do? 

![IMG_20220312_201722](https://user-images.githubusercontent.com/25499930/158032034-1f747984-d619-4a9a-b907-3dd52b27cc67.jpg)

![IMG_20220312_201716](https://user-images.githubusercontent.com/25499930/158032022-d60a802b-c52e-4db0-8545-02394efe84ab.jpg)

**Comment by Spark-Concepts** [comment]
Most likely a bad connector (potentially corrosion,  contamination,  or plastic injection molding flash); please contact us directly at https://www.spark-concepts.com/contact-us-1/ for resolution
