### ISSUE TITLE
0-10v fine tune not working. 

### ISSUE THREAD

**Issue by Anson90** [Spark-Concepts/xPro-V5#123]
Hello. 
I have connected my 1.5kw Folin vfd to the 0-10v and ground pins on the toolhead interface and also to the relay pins beside it (as per instructions). 
switch on controller is on “pwm” and the spindle is set to pwm. Set my max and min speeds to 24000 and 8000 but when I hit command “M3S24000” I only get 2.4v instead of 10v and the fine tune does nothing. The Pwm input is 5v when I exicute the command of that helps at all 🤷‍♂️

I’ve set and reset my parameters three times now and am now thinking it may be a hardware issue?  

Any ideas?

**Comment by Spark-Concepts** [comment]
Also please copy and paste your settings ```$S```

Also, disconnect (unplug) EVERYTHING on your controller with the exception of 24V; 
then enter ```M3 S24000``` and re-measure the 0-10V and PWM; what do you measure on each output?
