### ISSUE TITLE
GRBL Travel distance issues

### ISSUE THREAD

**Issue by TTALON541** [Spark-Concepts/xPro-V5#124]
I have been stuck on this for a couple of weeks. Calibration issues
Starting at the 0 positions, I move X 10in, however, it only moves 9.449 inches. with settings at 8 micro-steps and ``and 175 Step/mm.

Now if change the Steps/Mm ($100) to 200Steps/mm then I get the correct travel distance, but my motor ends up stalling out at long distances, so example, starting from 0, if I move 20inches it stalls towards the end, almost like stepper doesn't have enough power.

so 175steps/mm works just fine however the travel distance off by apx half in
or 200steps/mm stalls out but the distance is correct.
Current settings, 100$ I change back and fourth 175 to 200 bu3t the rest  are ggood
$+
$0=4 (Step pulse time, microseconds)
$1=255 (Step idle delay, milliseconds)
$2=0 (Step pulse invert, mask)
$3=1 (Step direction invert, mask)
$4=0 (Invert step enable pin, boolean)
$5=0 (Invert limit pins, boolean)
$6=0 (Invert probe pin, boolean)
$10=1 (Status report options, mask)
$11=0.010 (Junction deviation, millimeters)
$12=0.002 (Arc tolerance, millimeters)
$13=0 (Report in inches, boolean)
$20=0 (Soft limits enable, boolean)
$21=0 (Hard limits enable, boolean)
$22=1 (Homing cycle enable, boolean)
$23=3 (Homing direction invert, mask)
$24=200.000 (Homing locate feed rate, mm/min)
$25=2500.000 (Homing search seek rate, mm/min)
$26=250.000 (Homing switch debounce delay, milliseconds)
$27=2.500 (Homing switch pull-off distance, millimeters)
$30=24000.000 (Maximum spindle speed, RPM)
$31=0.000 (Minimum spindle speed, RPM)
$32=0 (Laser-mode enable, boolean)
$N1=
$N0=
$33=5000.000
$34=0.000
$35=0.000
$36=100.000
$100=175.000 (X-axis travel resolution, step/mm)
$101=175.000 (Y-axis travel resolution, step/mm)
$102=175.000 (Z-axis travel resolution, step/mm)
$103=175.000
$104=175.000
$105=175.000
$110=2500.000 (X-axis maximum rate, mm/min)
$111=2500.000 (Y-axis maximum rate, mm/min)
$112=2500.000 (Z-axis maximum rate, mm/min)
$113=2500.000
$114=2500.000
$115=2500.000
$120=200.000 (X-axis acceleration, mm/sec^2)
$121=200.000 (Y-axis acceleration, mm/sec^2)
$122=200.000 (Z-axis acceleration, mm/sec^2)
$123=200.000
$124=200.000
$125=200.000
$130=760.000 (X-axis maximum travel, millimeters)
$131=765.000 (Y-axis maximum travel, millimeters)
$132=150.000 (Z-axis maximum travel, millimeters)
$133=765.000
$134=300.000
$135=300.000
$140=1.800
$141=1.800
$142=1.800
$143=1.800
$144=1.800
$145=1.800
$150=0.125
$151=0.125
$152=0.125
$153=0.125
$154=0.125
$155=0.125
$160=8
$161=8
$162=8
$163=8
$164=8
$165=8
$170=16
$171=16
$172=16
$173=16
$174=16
$175=16

**Comment by Spark-Concepts** [comment]
https://github.com/Spark-Concepts/xPro-V5/issues/162#issuecomment-1208752616
