### ISSUE TITLE
Y axis Stepper Motor stopped working during job. Red Light constantly on

### ISSUE THREAD

**Issue by Nepmuk** [Spark-Concepts/xPro-V5#127]
I have a issue with my CNC xpro v5.

During a job on of the 2 y axis Stepper Motor stopped working and the x gantry got twisted.

The machine stopped and I tested the mechanics. Both y axis lead screws with the gantrys can be moved easily by hand. (I disconnected the motors from the leadscrew to test)
Now while jogging the y axis the y motor did not turn  smooth and also not in one direction. When switching the 2y axis motors the problem occures on the 2. Motor. So I think there is a problem with the stepper driver. Even after switching off and restarting the red indicator light on the y axis on the side of the cncpro is still constantly on.
Can u help me identify if it is a software or hardware problem? And hopefully we can solve it. The controller is around 6 month old and has only maybe 15 working hours and only with soft wood...

Thanks in advance

**Comment by Jin454** [comment]
Hi. Did you solve the problem? I have the same issue + Motor connected to Y make loud noise when hold.

**Comment by Nepmuk** [comment]
Unfortunately not. I hope to spark concept can step in with a idea.

**Comment by Spark-Concepts** [comment]
Nepmuk, if you haven't already please contact us via https://www.spark-concepts.com/contact-us-1/
