### ISSUE TITLE
Running homing seq. from SD-card.

### ISSUE THREAD

**Issue by kmjonsson** [Spark-Concepts/xPro-V5#13]
Trying to run the a homing seq. on my machine from SD-card, 
that will also do some other setup later, but it fails with a bang.

It feels like the machine is not changing direction after the first hit on the limit switch and smashes into the wall.

If I run $HX in the web GUI it works like a charm. Even if I only have one $HX in the machine it fails.

**Comment by Spark-Concepts** [comment]
Did you ever find a solution to this issue? If not please repost
