### ISSUE TITLE
How to force firmware update?

### ISSUE THREAD

**Issue by Rfleischgewehr** [Spark-Concepts/xPro-V5#136]
Hello. I did a firmware update but there was a bug right in the middle of the update. 
The problem is that now I can no longer connect to USB or wifi. 
So I would like to know how to bootload the firmware 
Thank you.

**Comment by Spark-Concepts** [comment]
Rfleischgewehr, instructions and tools can be found here: https://github.com/Spark-Concepts/xPro-V5/tree/main/Firmware/Old%20Firmware/flash_download_tool
