### ISSUE TITLE
Help me before I destrod my machen :(

### ISSUE THREAD

**Issue by ghalib1399** [Spark-Concepts/xPro-V5#137]
Hi all I have problem to connect xpro v5 with VFD, and I tried many option but does not work with me!(Issues #109 ).
  if your (cnc machine) is working smoothly, please share a visual representation of how you connected xpro v5 with VFD .

**Comment by spydercnc** [comment]
Try and search for my name on here. I posted the link to get the RS485 working, two wires and the correct firmware on the XPro and around 6 lines changed on the VFD. I will try and look for it in the morning. Easy when it all falls into place.🙂

**Comment by ghalib1399** [comment]
> Try and search for my name on here. I posted the link to get the RS485 working, two wires and the correct firmware on the XPro and around 6 lines changed on the VFD. I will try and look for it in the morning. Easy when it all falls into place.🙂

Thank You very much 
You guided me to solve my problem !!! it was software not hardware ! I install old firmware(CNC_xPRO_V5_XYYZ_485_NC) and work fine
