### ISSUE TITLE
General Firmware Issues

### ISSUE THREAD

**Issue by pborges** [Spark-Concepts/xPro-V5#138]
It is very difficult to find the "latest" firmware version. My xPro is reporting ```UI: 2.1b52 / FW: 1.3a (20201212)``` is this (1.3a) the latest version? 

There is no mention of what version is in https://github.com/Spark-Concepts/xPro-V5/tree/main/Firmware also there is no ```XYAZ``` variations of firmware in the pre-compiled firmwares, only in the "old firmware" folder.

Am I missing something?

**Comment by Spark-Concepts** [comment]
New firmware has been released
