### ISSUE TITLE
problema con el controlador en eje y 

### ISSUE THREAD

**Issue by jose1094** [Spark-Concepts/xPro-V5#139]
espero esten bien tengo un problema con el eje y pero el problema viene desde el controlador ya revise cableado  y los motores pero estan bien,  pero  cuando conecto el motor al puerto y2 se activa un bombillo rojo y el motor cuando se mueve empieza a vibrar  como si se fuera a salir el motor de si mismo. espero una colaboracion urgente ya que no e podido utilizar  ni una vez y estoy muy triste con este controlador ya que tiene multiples fallas.
![WhatsApp Image 2022-05-06 at 7 54 26 PM](https://user-images.githubusercontent.com/91394247/167231834-4140f694-721a-4c59-b2b7-19dd2fdd4808.jpeg)

https://user-images.githubusercontent.com/91394247/167231830-0d89a8a3-31cc-4437-b00e-3b198349e36a.mp4

https://user-images.githubusercontent.com/91394247/167231832-3aaec4b0-3efc-4111-a1cf-b4c78a4be2c4.mp4

.

**Comment by jose1094** [comment]
Hola buenas tardes ya revise todo el cableado y los motores y el problema
persiste en el puerto Y
Cuando cambio el motor de puerto funcionan bien ambos motores.

(si me quivoque en el momento que dije que era el Y2 al momento de redactar)

Muchas gracias.

**Comment by Spark-Concepts** [comment]
It sounds like you may have a faulty unit - please use the contact us page found here for resolution (please be sure to provide when and where you purchased your xPro) : https://www.spark-concepts.com/contact-us-1/
