### ISSUE TITLE
xPro-V5 not responsive

### ISSUE THREAD

**Issue by RidwaanN** [Spark-Concepts/xPro-V5#145]
Hi I have my xPro-V5 just under 2months now, it's been working fine all the time.
I last cut 2 weeks ago Friday. Monday passed i switched everything on as normal. Plugged in the controller via USB-C cable as usual and opened CNCJs.
As usual I clicked on Reset and Unlock. Where i would usually get all my configurations printed out on the left column - Nothing. The port is open, xPro V5 is powered on (Green light is on and blue usb light is on). It wont unlock or reset. Common response to anything is $X
I have tried closing the port and CNCJs, even restarting laptop and also tried connecting via LaserGRBL which will not connect successfully.

I have tried to connect to the xPro-V5s wifi network however not network is being found.

![image](https://user-images.githubusercontent.com/106156650/170026803-2a2effba-434c-403d-9a45-0bd4c57864ed.png)

**Comment by RidwaanN** [comment]
Hi. It appears to be in my device manager...
![image](https://user-images.githubusercontent.com/106156650/170245443-709352e5-b016-4f62-8e7c-4cd7c4c02b74.png)

**Comment by RidwaanN** [comment]
![20220525_115917_resized](https://user-images.githubusercontent.com/106156650/170245611-32c26c58-0ac5-4a9e-952e-b81ca1a78154.jpg)
![20220525_115911_resized](https://user-images.githubusercontent.com/106156650/170245629-f204cb26-22f7-4c98-be5f-4e533abd5cca.jpg)

**Comment by Mboss32** [comment]
Try opening the port in CNCjs, then pressing the "reset" button on the side of the controller

**Comment by RidwaanN** [comment]
> Try opening the port in CNCjs, then pressing the "reset" button on the side of the controller

I have tried that. I even held it in for +/- 20 seconds with no response.

**Comment by Jennywhite2** [comment]
> > Try opening the port in CNCjs, then pressing the "reset" button on the side of the controller
> 
> I have tried that. I even held it in for +/- 20 seconds with no response.

Hello RidwaanN,may i know,where u come from,,malaysia?

**Comment by Spark-Concepts** [comment]
Has this issue been resolved?

**Comment by Jennywhite2** [comment]
![Uploading IMG_20220819_221215.jpg…]()

**Comment by Jennywhite2** [comment]
![IMG_20220819_221215](https://user-images.githubusercontent.com/106455862/186949833-5052415b-0e5d-43f5-908d-36a15ac26b28.jpg)
