### ISSUE TITLE
Y limits not working

### ISSUE THREAD

**Issue by Wolfpackcustoms** [Spark-Concepts/xPro-V5#148]
im having issues with the Y and Y2(B) limit switches. I have tested both switches from the xpro connections to the switches and both test the same as the X and Z axis switches. 

I have updated the Xpro with the xPV5xyyz.bin as per the forums and installed the CNC_xPRO_V5_XYYZ_NC.bin as the software file. In CNCjs (1.9.22) i can get it to register the z and x axis as hard limits but neither of the Y will register as a hard limit. 

Can you advise as to how i can resolve this issue? 

Its fitted on a custom built CNC plasma table (belt drive y and x with lead screw Z)

**Comment by Spark-Concepts** [comment]
Are you still having issues with the Y hard limits? If so, please post your settings $S - also provide a picture of your limit switch wiring on your xPro
