### ISSUE TITLE
More VFD issues after firmware update. :( 

### ISSUE THREAD

**Issue by spydercnc** [Spark-Concepts/xPro-V5#154]
Using xPro5 with a 1.5 water-cooled VFD. Got the system working in January via RS485 and it has worked well, seamless for the most part actually. There were a few connection issues that required a reset nearly every time I switched the xPro5 on, decided to load the newer debug firmware. Eventually managed to get the WebUI working and flashed it using the over air function.     The spindle was loaded in GRBL, and communicated with the expected messages and then with a error message and no RX response. GRBL now runs a continuous loop of error messages and will not allow me to enter any new $ lines. I reloaded/entered the VFD codes and double checked, all wiring was shielded and installed and as above was working. I have fitted two 120K resistors to both ends of the RS485 wires. There is a red light flashing on the xPro but no alternating green light. Suggestions welcome. :(

**Comment by spydercnc** [comment]
Update and a shoutout for CNC3D Commander. Used their update tool, downgraded the firmware to the previous RS485 NO.Bin file, added the $spindle /type and a little green light started flashing  with everything springing into life. Life can be simple at times-begs the question why it had to be complicated then??

**Comment by Spark-Concepts** [comment]
Try installing the latest firmware as of July 2022 - If you're still having issues read https://github.com/Spark-Concepts/xPro-V5/issues/164#issuecomment-1208726453
