### ISSUE TITLE
Limit switch /vfd issue

### ISSUE THREAD

**Issue by Bentowle** [Spark-Concepts/xPro-V5#157]
I have been having a issue with my vfd, if I unplug the z axis limit from the control box I have no problems, when I move the limit switch near the box the spindle rpm error happens .

**Comment by Staggeble** [comment]
I fixed this issue by connecting the shielding of the limit switch to the ground.

**Comment by Staggeble** [comment]
I used this guide for my setup. https://wiki.printnc.info/spindle_settings.pdf

**Comment by Bentowle** [comment]
i ended up needing to add chokes.
