### ISSUE TITLE
driver files not available

### ISSUE THREAD

**Issue by scifunk909** [Spark-Concepts/xPro-V5#158]
I'm having issues connecting my CNCproV5 to my W10 PC where I'm running CNCjs. I've downloaded the CP210x driver zip file but the files it says to install aren't in the zip folder

**Comment by Bentowle** [comment]
https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers
the universal windows didnt work for me i need the other one. i had the same issue when i download from the link they give you.

**Comment by scifunk909** [comment]
Thank you for replying. I did eventually find this link too.
