### ISSUE TITLE
Unable to set steps per mm

### ISSUE THREAD

**Issue by scifunk909** [Spark-Concepts/xPro-V5#162]
I've tried numerous equations to get the axis travel correct but nothing is working.

**Comment by Spark-Concepts** [comment]
If your screw goes 2mm per revolution. You would divide the number of steps per rev by that. So 200 steps/2mm.... eg 100 steps/mm

What machine are you configuring - also, belt or screw?

**Comment by Spark-Concepts** [comment]
if this helps...

You will need to change the following settings:
```
$100= (x, step/mm)
$101= (y, step/mm)
$102= (z, step/mm)
```
Type $$ in the command window and make note of the following micro step settings
```
$160 = (x, microsteps)
$161 = (y, microsteps)
$162 = (z, microsteps)
```

... and will depend on the stepper motor your using - for example: typical NEMA 17 motors are rated at 200 steps per revolution and you will need to do some math:
1. Move each axis by rotating the  the applicable stepper motor 1 revolution and measure the displacement in mm
2. Divide 200 by the displacement in mm you determined in step 1
3. Multiply and record the value from step 2 above with the applicable axis microstep value (this will be your $100, $101, and $102 value(s)

for example (x axis):
- NEMA 17 motors are rated at 200 steps per revolution
- ex. $160 = 8
- ex. 20mm per x stepper revolution
- 200-steps/revolution ÷ 20mm/revolution = 10-steps/mm
- 10-steps/mm x 8-microsteps = 80-steps/mm
- Type ```$100=80``` in command window 
- You will do this for each axis
