### ISSUE TITLE
Hello,,im using xprov5 

### ISSUE THREAD

**Issue by Jennywhite2** [Spark-Concepts/xPro-V5#163]
![IMG_20220717_024823](https://user-images.githubusercontent.com/106455862/179368298-cdd3a773-c3bb-452f-92cd-086d85cd5048.jpg)
Did my wiring is correct,,im put Ac power to power supply then loop/jump to vfd,, im using xpro v5,,,can some one sharing wiring diagram xprov5,,,because on github im not clear about wiring..

**Comment by RoboDaRock** [comment]
The photos are not clear enough to make out. Can you take some close up shots.

**Comment by spydercnc** [comment]
The other issue I had originally is that I used 4 core wire. Using a twisted pair, shielded, wire sorted that out as well. I have also put a 100ohm resistor over the terminals, although it was working without it.

**Comment by RoboDaRock** [comment]
Hi spydercnc can you email me the firmware file you used my email roccoszabo@gmail.com thanks in advance

**Comment by RoboDaRock** [comment]
Hi spydercnc  any chance you could email me the firmware you use  thanks in
advance

**Comment by Spark-Concepts** [comment]
RoboDaRock,

Were you able to sort things out? If not please post a more clear image of your current wiring - also please review 
 https://github.com/Spark-Concepts/xPro-V5/issues/164#issuecomment-1208726453

**Comment by Spark-Concepts** [comment]
RoboDaRock,

That was my mistake, that last comment requesting images was directed toward Jennywhite2. I see you re-posted on the other issues thread. I totally get and don't blame you for being frustrated.

I believe we are shipping you a new unit which I personally tested on our rig via multiple 3hr test jobs running a rs485 spindle while monitoring and verifying all system functions before packaging and shipping.
