### ISSUE TITLE
Laser & Huanyang Spindle

### ISSUE THREAD

**Issue by Pepoch** [Spark-Concepts/xPro-V5#180]
I have a CNC router with Xpro-v5 and I'm trying connect a laser module, I still have the spindle working, and I want to add a laser and use one or other just by programming or controlling with cncjs
Does anybody know how to do the wiring and programming ?

**Comment by Spark-Concepts** [comment]
Have you had any luck with this?

* Which laser and spindle are you using?
* Your configuration can be established assuming your VFD is connected via rs485 and selected by flipping the PWM/RS485 switch on the side as well as definging the spindle type as ```$spindle/type= huanyang``` or ```$spindle/type=pwm```

I've closed this issue for now, however please feel free to reopen this issue if you still need assistance.
