### ISSUE TITLE
Help with Wifi station

### ISSUE THREAD

**Issue by FlyerLife22** [Spark-Concepts/xPro-V5#191]
Hi Folks, 

So far I have been loving the controller, does exactly what I want it to do until now.  The range of the on board wifi is pretty limited and I am trying to add it to my home network.  I see that I need to swap over to station mode for the radio, but once I did I lost contact with the unit... 

How can I get connected to it again??

**Comment by Spark-Concepts** [comment]
It's easiest to configure via USB and using CNCjs (or really any serial terminal program). To reset wifi settings type the following ```RST=wifi```

Then to connect to your Wifi, please follow this guide:
https://github.com/bdring/Grbl_Esp32/wiki/Setting-up-the-Wifi-Network
