### ISSUE TITLE
spindle rs485 unresponsive 8

### ISSUE THREAD

**Issue by ghalib1399** [Spark-Concepts/xPro-V5#193]
Hi all
when I send file to run, its working for 1 minute then spindle stop moving but the head still running! with (spindle rs485 unresponsive 8) message. 
I press pause then I press run againe , its moving  again then stop ...

can any one help me ?

**Comment by Spark-Concepts** [comment]
This is typically a noise issue via the VFD:
- Ensure RS485 wiring is less than 1 meter in length, twisted, and connected properly (resistors are likely needed in your case)
![image](https://user-images.githubusercontent.com/8650709/183530101-65122f53-1293-4272-8e1c-271b757b6c80.png)

In cases where VFD noise is particularly severe (typically only encountered with VFD's on 220V mains); you may need to install an RS485 isolator - see https://github.com/Spark-Concepts/xPro-V5/issues/164#issuecomment-1219037733
   ![rs485_Isolated](https://user-images.githubusercontent.com/8650709/186558328-6ece075d-9681-4c47-aa0b-d36685725601.jpg)

**Comment by ghalib1399** [comment]
Thank you for your help. my problem was from usb cable connecting laptop to  xPro-V5.

**Comment by Spark-Concepts** [comment]
Gotcha, I'm glad you got it working!
