### ISSUE TITLE
Burned chip

### ISSUE THREAD

**Issue by TRUDIM** [Spark-Concepts/xPro-V5#22]
Hi!

While putting back my XYZ touch probe back to where it rests the magnet touched somewhere on the touch probe board and smoke came out of the xPro. Here's a picture of the burned chip.
What is this chip for, can I fix it myself (I'll buy the part and give it to a professional to replace it)?![D10415FA-3243-4E93-9ED1-E9A4AB133412](https://user-images.githubusercontent.com/81646060/115205683-7cc19500-a102-11eb-9133-e7061d9893da.JPG)

**Comment by Spark-Concepts** [comment]
TRUDIM,

Please email Bill@spark-concepts.com - I can give you a couple options
