### ISSUE TITLE
M4 command throws ERROR:20 when spindle mode is used.

### ISSUE THREAD

**Issue by Slixxor** [Spark-Concepts/xPro-V5#24]
Is there a reason why you guys locked out the M4 command when in spindle mode?

**Comment by Mboss32** [comment]
Again, this is our hardware-specific code - there is no direction output from the hardware.  The outputs are speed and enable so the default is to lock out the M4 option to not cause issues.  For the non-hardware specific code please check out the awesome work by Bart Dring here (https://github.com/bdring/Grbl_Esp32)
