### ISSUE TITLE
Power Switch not working?

### ISSUE THREAD

**Issue by jiangmf** [Spark-Concepts/xPro-V5#29]
I'm very new to the world of CNC and wiring up circuits so forgive me if I'm making some kind of newbie mistake.

I have a very simple set up currently, just 4 motors, 24V power and USB connected. The power switch does not seem to be doing anything, even in the OFF position, the 24V indicator light is ON, and I'm able to spin the motors with CNCjs. Everything still works when the switch is in the ON position as well

Is this normal? if so, what do I need to do to get the power switch working?

![resized-image-Promo](https://user-images.githubusercontent.com/11680350/121795219-aa93f900-cbdc-11eb-994c-23254578adac.jpeg)

**Comment by Spark-Concepts** [comment]
Jiangmf,

That's an interesting one... The motors and green LED should not be operational while in O. F. F. mode. Most certainly sounds like a switch issue.

When toggled, does the switch detent feel loose -or- do you get a satisfying click?

**Comment by jiangmf** [comment]
No the switch clicks and feels very firm in both positions.

**Comment by Spark-Concepts** [comment]
My most sincere apologies  for not replying to your last comment.

If you wouldn't mind please post or email a picture of your current setup - mainly the wiring (motors, limit switches, power supply, etc...)

Post here, or email to bill@spark-concepts.com & mike@spark-concepts.com

Thanks!

**Comment by Spark-Concepts** [comment]
Hmm, very odd, that's a first! 

Please contact us at https://www.spark-concepts.com/contact-us-1/ for options

**Comment by jiangmf** [comment]
Closing this issue as somehow the switch magically started working as I was putting everything together for a photo. Don't think I've made any changes to any of the connections other than maybe flashing the firmware to CNC_xPRO_V5_XYYZ_485_NC (don't recall if it started working before or after the flash)
