### ISSUE TITLE
Firmware help

### ISSUE THREAD

**Issue by GeorgeSmith** [Spark-Concepts/xPro-V5#31]
I tried to update the firmware on my CNC xPRO V5 following the steps here
https://github.com/Spark-Concepts/xPro-V5/wiki/Checking_firmware_and_upgrading

I thought it had worked then this happened. 

![image](https://user-images.githubusercontent.com/6382555/122200847-86dbf600-ceef-11eb-88e4-03956f3eff04.png)

I cant find any information about "Identification requested" on github. I defiantly have a NC switch attached and have changed the jumper inside to EStop Enabled. The EStop LED is always on regardless of whether the jumper is in the enabled or disabled position or whether the switch is open or closed.

Any help would be appreciated greatly.

**Comment by pacman171** [comment]
Have a look at issue number #21 this might help you? Look at your emergency stop button. I am not an expert :)
