### ISSUE TITLE
Steppers only work after connecting twice

### ISSUE THREAD

**Issue by allistar** [Spark-Concepts/xPro-V5#32]
I use CNCjs to control my XPro. When I start CNCjs I connect it to the XPro (using USB). I then run the homing cycle. The CNCjs display shows the Z axis moving but the stepper isn't doing anything. I then disconnect and reconnect after which it works as expected. My process now when starting CNCjs is to connect, disconnect, then connect before using the machine. This issue happens every single time. In both cases when I connect I hear the stepper power on (a slight "snapping" sound).

What explains the behaviour and is there anything that can be done to fix it? I'm running the latest XYYZ RS485 firmware.

**Comment by Spark-Concepts** [comment]
After connecting the COM port in CNCjs, press the reset button on the side of the xPro-V5 to sync to CNCJS

**Comment by allistar** [comment]
Thanks. Do I need to do that every time I start the computer and/or the XPro?

**Comment by pacman171** [comment]
Hi Allistar, I have to do the same every time. I switch the vfd and xPro on, then about 30 sec later I have to press the reset button. Also whenever I startup, it always shows an alarm.

**Comment by Spark-Concepts** [comment]
Before you connect to the serial port in CNCjs check the "Enable hardware flow control" - this should eliminate you having to manually press the reset every time you connect.

![image](https://user-images.githubusercontent.com/8650709/122490326-c10ccc80-cfaf-11eb-967b-78b29ede329e.png)

**Comment by pacman171** [comment]
Works for me, thanks!

**Comment by allistar** [comment]
I always have "Enable flow control" set. I think my issue is that I wasn't giving the XPro enough time to start up. Now I turn on the VFD and XPro, then the computer and by the time the PC has started up and I run CNCjs this issue doesn't occur. I'm reclosing this issue, thanks for the help.
