### ISSUE TITLE
Updated Firmware and now i cant change the default GRBL settings

### ISSUE THREAD

**Issue by timm052** [Spark-Concepts/xPro-V5#36]
After updating the firmware to the latest version from whatever the controller came with i can no longer change the default GRBL settings after falshing the cnc will work fine allowing movement all axis. But upon setting the correct settings for my cnc the motor will cease to move GRBL still registers the motors as moving but they will not move i have attempted going back to the firmware from the included SD and fashing it multiple times. When applying my setting via the command line the controller gives this error [MSG:Error: out of RMT channels] this error on pops up if i try to set the setting via macro if i do it line by line no error pops up but the motors cease to move anyway. Any help would be much appreciated.

**Comment by Spark-Concepts** [comment]
Could send commands $S and $i to the controller and post the responses?

**Comment by timm052** [comment]
I reflashed the firmware a few more times and did some resets eventually it seems to have come good.
