### ISSUE TITLE
WebUI password

### ISSUE THREAD

**Issue by Project487** [Spark-Concepts/xPro-V5#41]
Hi, I want to change my access point (AP) password and can currently connect by wifi using the default password.  The AP password set appears to have 6 characters (****** starred out) rather than the 8 characters of the password (123..) I used to connect.  Can I safely change the password with the ESP3D interface?  Why are only 6 stars showing when 8 characters were required?
Thanks

**Comment by Spark-Concepts** [comment]
Yes you can safely change, the password must be a minimum of 8 characters, but only 6 stars will show regardless of password length.  Just showing that the field is hidden.
