### ISSUE TITLE
New Xpro v5 new issues , now it makes the stepper motors scream which is new and endlessly clicks in a rhythm,  what the he'll is going on now this is the second controller replacing the first one that didn't work

### ISSUE THREAD

**Issue by DanVass1979** [Spark-Concepts/xPro-V5#48]

**Comment by seaw14** [comment]
Yeah the last 4 I've received are doing exactly this as well. Any help would be nice.

**Comment by seaw14** [comment]
I have just checked my stock pile of them and the latest 7 controllers have this issue.

**Comment by Spark-Concepts** [comment]
The rythmic ticking is likely the relay opening and closing with a 485 version of firmware loaded.  Check to make sure the PWM / 485 switch is fully seated in the 485 position.  

The loud motor whine is the chopper frequency hanging out in the audible range.  this firmware should help 
[CNCxPROv5_XYYZ_NC_BM3Dtune.zip](https://github.com/Spark-Concepts/xPro-V5/files/7158340/CNCxPROv5_XYYZ_NC_BM3Dtune.zip)
