### ISSUE TITLE
Macro Limitations

### ISSUE THREAD

**Issue by samwilt** [Spark-Concepts/xPro-V5#5]
Am I correct that you can't run multiple lines of g code via the macro section? I was trying to save a XYZ probe macro but I can't get this to work.

Appreciate your comments

Thanks

**Comment by Slixxor** [comment]
GRBL does not support internal macros. It needs the sender to control this.

Try using our Commander software. It has a Macros section and also has an easy probing wizard.

https://www.youtube.com/watch?v=WTRjHIGY73M

I'm pushing through a release soon that will support the xPRO V5s extended features,
