### ISSUE TITLE
Which software to use for 0-10V firmware

### ISSUE THREAD

**Issue by cdo1955** [Spark-Concepts/xPro-V5#56]
I am trying to go to the 0-10 volt PWD firmware for control of my VFD since we could never get the RS485 firmware to work.
But the names of the newest firmware don't have the letters PWM in it. So I can't tell which  to chose. What's the the correct firmware for a NC  XYYZ system PWM system?

**Comment by cdo1955** [comment]
could I also see a drawing of exactly how to land the 0-10 v wires on the VFD?

**Comment by Spark-Concepts** [comment]
Hi cdo1955 

With the new firmware each spindle build is included.  You will need to define $Spindle/Type = PWM  (this activates PWM and the 0-10V outputs).

Wire like this for the xPRO side.  How they land on the VFD will depend on the manufacturer of the VFD

![image](https://user-images.githubusercontent.com/8650709/134060982-34777cba-36cd-44a7-9c35-60252f76fc40.png)
