### ISSUE TITLE
conexion cableado laser al xpro v5 

### ISSUE THREAD

**Issue by jose1094** [Spark-Concepts/xPro-V5#63]
buenas tardes estoy intentando conectar un laser a mi xpro v5 el laser tiene 3 cables PWM, 12- y 12+ y el controlador tiene EN, PWM y GND. como se aria la conexión de los cables y que me tocaria configurar en el xpro v5.
muchas gracias.
![WhatsApp Image 2021-09-25 at 4 59 17 PM](https://user-images.githubusercontent.com/91394247/134821146-5192e3dc-f67d-4611-a1fa-cc40864b57b8.jpeg)
![WhatsApp Image 2021-09-25 at 5 03 45 PM](https://user-images.githubusercontent.com/91394247/134821148-f9c52866-996d-41fb-9686-915cdf01503c.jpeg)

**Comment by Spark-Concepts** [comment]
Buenas noches, ¿qué modelo de láser tienes? ¿Cuál es el voltaje de entrada máximo?

1. PWM (cable amarillo) se conecta al PWM en el x Pro

2. 12- (cable negro) a GND en xProV5 y GND en suministro de 12V

3. 12+ (cable rojo) a +12V suministro
