### ISSUE TITLE
Error 13 Door

### ISSUE THREAD

**Issue by hellboytat** [Spark-Concepts/xPro-V5#72]
I want to add a E stop button but am running into a few issues.

I have installed the NO firmware. I have checked the jumper cables ( Its on disable E-Stop and 5v).

If I add the 3.81mm connector without any wires I get no error and it works. If I add a wire coming out of the SIG pin that leads nowhere it triggers the error. I think there is a defect here

Any advice?

**Comment by Spark-Concepts** [comment]
Does the board mounted 3.81 receptacle housing seem loose? It might be worth inspecting for debris/cold solder joint (try the steps below first - if your issues persist, please let me know)
 
Does it matter which terminal the wire is installed before triggering the error (right or left)? If you have a digital multimeter, please measure DC voltage across 3.81mm e-stop connector & let me know if you see a voltage reading of ~5V.

Also, please move the "GPIO logic" jumper to "24V" and "out" & re-test and re-measure voltage (you should see ~24V)

**Comment by spidee601** [comment]
Make sure your Ebutton isn't already pushed down.  I spent about an hour trying to figure it out, only to find that I forgot to twist the ebutton to disengage it.
