### ISSUE TITLE
xpro v5 wifi issue

### ISSUE THREAD

**Issue by danmillier** [Spark-Concepts/xPro-V5#75]
trying to connect machine to my wifi and control on web page but is going into ap mode

**Comment by squarkyd** [comment]
I have the same issue, when you click next the icons at the top change but the rest of the window does not update.
Have tried multiple devices and browsers, it's a giant pain in the ass and causing me no end of problems.

**Comment by mwipp66** [comment]
I have the same issue as well. Exact same issue as squarkyd where the setup pane does not move past selecting language. Updating firmware did not fix this either

**Comment by Spark-Concepts** [comment]
***note: the xProV5 hardware is 2.4GHz only (it will NOT connect to 5G wifi)***

Here are some methods to determine your current [settings](https://github.com/Spark-Concepts/xPro-V5/wiki/Changing-settings) via the [USB/Serial port](https://github.com/bdring/Grbl_Esp32/wiki/Serial-Port-Setup-and-Usage) or [USB/WebUI](https://github.com/Spark-Concepts/xPro-V5/wiki/USB_guide#gcode-senders). 

$I This will list the basic connection information
$System/Stats This list Wifi stuff as well as a lot of system information
$WiFi/ListAPs This list all of the Wifi access points found and the signal strength

Connected via USB and using one of the methods identified above and using the terminal window:


1. Document your machine settings `$$` and/or `$S`
2. Reset WIFI settings via `$RST=@` ...or reset ALL settings to factory default `$RST=*`
3. Enter the following via the terminal window
Here are the steps required to put it on your network ("YourSSID" = your wifi SSID and "Password" = your wifi password)

`$Sta/SSID=YourSSID`
`$Sta/Password=YourPassword`
`$Radio/Mode=STA`

**Comment by danmillier** [comment]
I get error # bad number format when I $RADIO/MODE=STA
