### ISSUE TITLE
problema cncjs o escala de los archivos 

### ISSUE THREAD

**Issue by jose1094** [Spark-Concepts/xPro-V5#83]
tengo un problema con el tamaño de mis archivos tengo una maquina de 1500x1500 pero monto un archivo de 160mm x 70mm y es mas grande que la maquina. espero alguien me pueda ayudar. muchas gracias.

![Captura de Pantalla 2021-11-07 a la(s) 3 45 22 p  m](https://user-images.githubusercontent.com/91394247/141705541-a3cb24a8-61eb-42cd-abfa-44b0bdda25ca.png)

![Captura de Pantalla 2021-11-07 a la(s) 3 45 06 p  m](https://user-images.githubusercontent.com/91394247/141705559-ce08ca34-457c-4699-87e2-bbc6000c5fc2.png)

![Captura de Pantalla 2021-11-07 a la(s) 3 44 55 p  m](https://user-images.githubusercontent.com/91394247/141705575-d60685f3-b284-41a8-bb8c-375ca90afcc8.png)

**Comment by MichaelMartinez** [comment]
No entiendo el problema. Una vez que encuentre la máquina 0,0, debe configurar el 0,0 de la pieza de trabajo. Si es más pequeño que el área de trabajo, funcionará bien. Le sugiero que busque algunos tutoriales básicos antes de comenzar. ayudarán enormemente.

**Comment by jose1094** [comment]
Es qke creo que el tamaño de la maquina en el rgbl está mal yo pongo un
archivo de 120mm*75mm y se sale mas grande que el tamaño de la maquina y la
maquina es de 1500*1500.
Muchas gracias
