### ISSUE TITLE
Schematic for xPro v5 and/or details on CPU and other chipsets

### ISSUE THREAD

**Issue by ColPaulR** [Spark-Concepts/xPro-V5#89]
I've got a Queenbee Pro 1500x1500 with xPro V5 being shipped now and have been reading a lot. Is there a schematic for the v5? I saw on Github the schematics for v1-v4. If not, can you tell me about which ESP32 CPU is in the v5. There was an image in the Images directory of an ESP-WROOM-32. Is that the chip still in use? Also, any details on the USB chipset? I'm looking to see if the v5 can serve as USB host. I'd like to run G code from the SD card and make some firmware mods to support a USB pendant.

**Comment by Spark-Concepts** [comment]
Obviously this is extremely late coming - however, if you're still looking for an answer 
1. ESP-WROOM-32
2. USB chipset is CP2102N
