### ISSUE TITLE
Splitting motor power from controller power.

### ISSUE THREAD

**Issue by Ferdinandderoo** [Spark-Concepts/xPro-V5#94]
Hello,
Are there schematic drawings available for the controller.
This would help a lot with splitting the motor power and controller power.
I would like to try and hack the controller this would help me a lot because the controller is everything I need.
I don't like mach3/4 controller's
I'm running the controller on a big 1500x1500 machine.
I'm running in to motor limitations and losing steps sometimes.
This would help me a lot.

Ferdinand

**Comment by Spark-Concepts** [comment]
Please use the contact-us on the spark-concepts.com site if you're still needing clarification
