### ISSUE TITLE
Possible to configure as XXYZ?

### ISSUE THREAD

**Issue by luckypants123** [Spark-Concepts/xPro-V5#95]
Is it possible to flip the X and Y axis assignments somehow?

I assume I need to tweak something in the firmware and compile, just looking for pointers on the correct way to do this.
I can see in CNC_xPRO_V5_Machine_Template.h:
```
// X motor connects to the 1st driver, and the X port on the case 
#define X_TRINAMIC_DRIVER       5160        
#define X_RSENSE                0.05f 
#define X_STEP_PIN              GPIO_NUM_12
#define X_DIRECTION_PIN         GPIO_NUM_14
#define X_CS_PIN                GPIO_NUM_17  

// Y motor connects to the 2nd driver, and the Y port on the case
#define Y_TRINAMIC_DRIVER       5160        
#define Y_RSENSE                0.05f
#define Y_STEP_PIN              GPIO_NUM_27
#define Y_DIRECTION_PIN         GPIO_NUM_26
#define Y_CS_PIN                X_CS_PIN  

// Y2 motor connects to the 3rd driver, and the Y2/A port on the case
#define Y2_TRINAMIC_DRIVER       5160        
#define Y2_RSENSE                0.05f
#define Y2_STEP_PIN              GPIO_NUM_33  
#define Y2_DIRECTION_PIN         GPIO_NUM_32  
#define Y2_CS_PIN                X_CS_PIN 
```
Although I feel like I cant just swap X/Y/Y2 to Y/X/X2 and the limit switch assignments without changing whatever is using those variables...

Any help would be appreciated, thank you!

**Comment by luckypants123** [comment]
I also found the below in GCode.cpp:
```
                     case 'X':
                        if (n_axis > X_AXIS) {
                            axis_word_bit               = GCodeWord::X;
                            gc_block.values.xyz[X_AXIS] = value;
                            axis_words |= bit(X_AXIS);

                        } else {
                            FAIL(Error::GcodeUnsupportedCommand);
                        }
                        break;
                    case 'Y':
                        if (n_axis > Y_AXIS) {
                            axis_word_bit               = GCodeWord::Y;
                            gc_block.values.xyz[Y_AXIS] = value;
                            axis_words |= bit(Y_AXIS);
                        } else {
                            FAIL(Error::GcodeUnsupportedCommand);
                        }
                        break;
```

Would swapping the axis assignments here have the desired effect as well?

**Comment by Spark-Concepts** [comment]
you should do this in the Machine configuration file (first post).  Just change Y2 to X2, then you will have an X Y X2 Z setup so most of the silkscreen will still be correct

**Comment by luckypants123** [comment]
Awesome, thank you!

**Comment by lagnat** [comment]
@luckypants123 Where you successful swapping X and Y?  Did you have to rebuild the firmware?

**Comment by luckypants123** [comment]
Yes, made the changes above and then compiled it following the directions in the wiki. 
wasn’t too difficult and gave me an XXYZ machine.

**Comment by lagnat** [comment]
What version of Esp32 did you install?  bdring/Grbl_Esp32 docs say 1.0.3 and nothing higher but it looks like they're at 2.0.2 so wondering if those are stale docs.

**Comment by luckypants123** [comment]
I believe I used the source available from the Spark Concepts GitHub. It’s definitely behind in version, but I didn’t want to experiment with using the code from somewhere else.

**Comment by lagnat** [comment]
The Spark Concepts README says to follow the instructions at the bdring/Grbl_Esp32 repo, however it also says to follow the instructions at https://github.com/espressif/arduino-esp32.  Can you check which version of Esp32  you used?

https://github.com/Spark-Concepts/xPro-V5-Firmware#compiling-firmware

**Comment by luckypants123** [comment]
About 2 weeks after this the controller died, so that marked the end of my xProV5 adventure. 

If I remember right though, you need to follow the instructions at both those places, as they each cover a different part of the process. However instead of using the source code from bdring/, I used it from the Spark Concepts GitHub, as that version of the Arduino sketch has all the pin assignments correct for the unit. 

To be honest I don’t remember exactly, but I do remember it was not clear.
